---
global:
  namespace: argocd
  defaultCluster: https://kubernetes.default.svc
  clusterName: non-prod
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
  defaultRepositories:
    - url: 'git@github.com:polarpoint-io**'
    - url: 'https://argoproj.github.io/argo-helm'
    - url: 'https://polarpoint-io.github.io/charts'
    - url: 'https://polarpoint-io.github.io/**'
    - url: 'https://pkgs.tailscale.com/helmcharts'
    - url: 'https://charts.crossplane.io/stable'
    - url: 'ghcr.io/stacklok/toolhive'
    - url: 'https://charts.jetstack.io'

privateGitCredentialsTemplates:
  - name: polarpoint-io
    url: "git@github.com:polarpoint-io/"

privateHelmCredentialsTemplates: []

privateGitRepositories: []

publicHelmRepositories:
  - name: argo-helm
    url: "https://argoproj.github.io/argo-helm"
  - name: stacklok-toolhive
    url: "ghcr.io/stacklok/toolhive"
    enableOCI: true

privateHelmRepositories: []

clusters:
  - name: deploy
    url: https://kubernetes.default.svc
    local: true
    labels:
      env: non-prod
      role: deploy
  - name: tooling
    url: "https://192.168.11.80:6443"
    labels:
      env: non-prod
      role: tooling

projects:
  - name: argocd-config
    permissions:
      admin:
        description: "Admin Access"
        groups:
          - polarpoint-argocd-admin
      rw:
        description: "Read-Write Access"
        groups:
          - polarpoint-argocd-rw
      ro:
        description: "Read-Only Access"
        groups:
          - polarpoint-argocd-ro
    destinations:
      - name: default
        namespace: "*"
        server: https://kubernetes.default.svc
    applications: []

  - name: foundational
    permissions:
      admin:
        description: "Admin Access"
        groups:
          - polarpoint-argocd-admin
      rw:
        description: "Read-Write Access"
        groups:
          - polarpoint-argocd-rw
      ro:
        description: "Read-Only Access"
        groups:
          - polarpoint-argocd-ro
    destinations:
      - name: default
        namespace: "*"
        server: https://kubernetes.default.svc
      - name: tooling
        namespace: "*"
        server: https://192.168.11.80:6443
    applications:
      - name: foundational-applications-controller
        url: 'git@github.com:polarpoint-io/argocd-foundational-applications.git'
        path: releases
        targetRevision: main
        valuesFiles:
          - values.yaml
          - global-values-non-prod.yaml
        namespace: argocd
      - name: foundational-applications-tooling
        url: 'git@github.com:polarpoint-io/argocd-foundational-applications.git'
        path: releases
        targetRevision: main
        valuesFiles:
          - values.yaml
          - global-values-non-prod-tooling.yaml
        namespace: argocd

  - name: controller
    permissions:
      admin:
        description: "Admin Access"
        groups:
          - polarpoint-argocd-admin
      rw:
        description: "Read-Write Access"
        groups:
          - polarpoint-argocd-rw
      ro:
        description: "Read-Only Access"
        groups:
          - polarpoint-argocd-ro
    destinations:
      - name: default
        namespace: "*"
        server: https://kubernetes.default.svc
    applications:
      - name: controller-applications
        url: 'git@github.com:polarpoint-io/argocd-controller-applications.git'
        path: releases
        targetRevision: main
        valuesFiles:
          - values.yaml
          - global-values-non-prod.yaml
        namespace: argocd

  - name: tooling
    permissions:
      admin:
        description: "Admin Access"
        groups:
          - polarpoint-argocd-admin
      rw:
        description: "Read-Write Access"
        groups:
          - polarpoint-argocd-rw
      ro:
        description: "Read-Only Access"
        groups:
          - polarpoint-argocd-ro
    destinations:
      - name: default
        namespace: "*"
        server: https://kubernetes.default.svc
      - name: tooling
        namespace: "*"
        server: https://192.168.11.80:6443
    applications:
      - name: tooling-applications
        url: 'git@github.com:polarpoint-io/argocd-tooling-applications.git'
        path: releases
        targetRevision: main
        valuesFiles:
          - values.yaml
          - global-values-non-prod.yaml
        namespace: argocd
